package com.main.auth.DAO;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * An entity User composed by three fields (id, login, password).
 * The Entity annotation indicates that this class is a JPA entity.
 * The Table annotation specifies the password for the table in the db.
 *
 * @author netgloo
 */
@Entity
@Table(name = "user")
public class User {

  // An autogenerated id (unique for each user in the db)
  @Id
  @GeneratedValue(strategy = GenerationType.AUTO)
  private long id;
  
  // The user's login
  @NotNull
  private String login;
  
  // The user's password
  @NotNull
  private String password;

  // ------------------------
  // PUBLIC METHODS
  // ------------------------
  
  public User() { }

  public User(long id) { 
    this.id = id;
  }
  
  public User(String email, String password) {
    this.login = email;
    this.password = password;
  }

  // Getter and setter methods

  public long getId() {
    return id;
  }

  @PersistenceContext
  public void setId(long value) {
    this.id = value;
  }

  public String getLogin() {
    return login;
  }

  @PersistenceContext
  public void setLogin(String value) {
    this.login = value;
  }
  
  public String getPassword() {
    return password;
  }

  @PersistenceContext
  public void setPassword(String value) {
    this.password = value;
  }

} // class User
